### ISSUE TITLE
使用amap脚本，高德加载非常缓慢

### ISSUE THREAD

**Issue by Paris0-0** [RuCu6/QuanX#2]
不知道是不是个例，全套使用大佬的脚本和规则，高德地图不管是导航，打车还是实时公交都非常慢甚至加载不出来，请问大佬可能是为啥

**Comment by RuCu6** [comment]
你配置geoip或者用asn分流了吗

**Comment by Paris0-0** [comment]
没有，基本除了必要网站其他全部final直连

**Comment by RuCu6** [comment]
分流没有reject amdc.m.taobao.com 这个地址吧

**Comment by Paris0-0** [comment]
没有哎，而且高德很奇怪，就算关了脚本也要过一段时间才恢复正常加载速度（期间后台杀过很多次），然后打开脚本一开始也不会很缓慢，过一段时间就会每步都卡

**Comment by RuCu6** [comment]
有数据支持吗   只根据这些阐述  无法定位问题

**Comment by Paris0-0** [comment]
最新版高德，卸载重装n次，应该与分流无关，只与amdc.m.taobao.com这个域名的重写有关，每次全新安装高德，只要没有这个域名的重写，就一切正常，如果打开了有它的重写（myblockads和amap脚本里都有）就会提示网络连接失败或丢失连接等。
如果先关闭包含该域名的重写，等高德加载完全后再打开myblockads或amap，高德一切加载正常，似乎有缓存
过一段时间后持续开启myblockads依然不影响高德功能，但持续开启amap似乎也是等缓存过期后就会全功能缓慢或丢失网络连接

**Comment by RuCu6** [comment]
这个域名会返回 dns 地址，如果这条禁用会导致高德脚本全部失效。但是你这种情况，我建议不要使用脚本

**Comment by Paris0-0** [comment]
是的，已经放弃了🫤
