### ISSUE TITLE
近期 bilibili 脚本导致 <我的> 页面 稍后再看按钮被屏蔽，此前未有此情况

### ISSUE THREAD

**Issue by jdjxk** [RuCu6/QuanX#4]
![bilibili](https://github.com/RuCu6/QuanX/assets/46536339/71b36e7f-798d-42fd-8f55-376e803cd461)

**Comment by rkmy** [comment]
我也是出现此情况，自哔哩哔哩更新后，哔哩哔哩的我的界面处的稍后再看板块没有显示了，哔哩哔哩版本为7.54.0(75400100)，quanX版本：1.4.2-817。
![282301905-bd8dbfe5-a496-4e23-b81e-006b42456320](https://github.com/RuCu6/QuanX/assets/38809548/a9b2b864-618c-456d-b5aa-f158544b3f1e)

**Comment by RuCu6** [comment]
已复现，今天晚上会修复。

**Comment by RuCu6** [comment]
已解决
