### ISSUE TITLE
台湾节点貌似匹配不到

### ISSUE THREAD

**Issue by okami-chen** [RuCu6/QuanX#7]
static=台湾节点, server-tag-regex=^(?i)(🇹🇼|台|台湾|台灣|TW|Tai|Taiwan).*$, img-url=https://raw.githubusercontent.com/RuCu6/QuanX/main/Icons/area/tw.png

**Comment by RuCu6** [comment]
无法匹配所有服务提供者的各种命名方案，请自行调整正则
