### ISSUE TITLE
bilibili 脚本导致 底栏<关注> 按钮被去掉了！

### ISSUE THREAD

**Issue by bruce322** [RuCu6/QuanX#8]
底栏<关注> 按钮没了：只有两个按钮

**Comment by RuCu6** [comment]
底栏哪里有关注按钮？

**Comment by bruce322** [comment]
![d20f21a941c1db2565d2d43a001ad40c](https://github.com/RuCu6/QuanX/assets/10057942/db13057f-f59c-41df-8cc6-6a92d9b456ba)

**Comment by RuCu6** [comment]
这个是动态按钮  不是常规粉色B站不推荐使用此脚本
